### PR TITLE
[WIP] Bring into the modern world!

### PR DESCRIPTION
**Pull request by NotTsunami**
Hey Andrew! I love Plumble, but there are still quite a few artifacts within the project, and I feel that we should bring a lot of things up to today's standards! If you don't agree with any of these changes please let me know!
- [x] Update dependencies to latest available version
- [ ] Update APIs to reflect latest versions of things and cleanup lint warnings
- [ ] Ask for permissions the Marshmallow way
- [ ] Restructure gradle files to look a lot cleaner
- [ ] Whitespace fixes
- [ ] Small UI updates/enhancements

### CODE REVIEW

**Comment by Tsunamical** [comment]
@acomminos Let me know what you like/don't like from the list and I can start working on it. Depending on your plans for 3.3.0 this may be a good milestone for 3.3.0 since none of these changes are major rewrites.

**Comment by acomminos** [comment]
These all look good to me, thanks.

With regards to NetCipher, my custom fork no longer has to be used; gradle/maven support has been added upstream.

**Comment by acomminos** [comment]
Upstream NetCipher is now used, fetched via jcenter.

**Comment by Tsunamical** [comment]
Alright, will rebase and begin working on this again. Was working on my own ROM and a few side projects :+1:

**Pull request closed without merging**
